version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.9
 build:
  commands:
   - sam build
   - export BUCKET=abhinandan-ci-lambda-001
   - export TEMPLATE=template.yml
   - export TEMPLATE_FILE_NAMEoutput_template_stag.yml
   - sam package --template-file $TEMPLATE --s3-bucket $BUCKET --output-template-file $TEMPLATE_FILE_NAME
artifacts:
 type: zip
 files:
  - $TEMPLATE
  - $TEMPLATE_FILE_NAME
 
  
