version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.9
 build:
  commands:
   - sam build
   # - export BUCKET=testapi-icici
   - export TEMPLATE=cfn.yml
   - export OUTPUT_TEMPLATE=output_template_stag.yml
   - sam package --template-file $TEMPLATE --s3-bucket $BUCKET --output-template-file $OUTPUT_TEMPLATE
artifacts:
 type: zip
 files:
  - $TEMPLATE
  - $OUTPUT_TEMPLATE
  
